FROM node:22.22-alpine3.23

WORKDIR /app

COPY frontend/package.json ./
RUN npm install

COPY frontend ./

ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]
